org: sparda
service: cors-proxy
configValidationMode: error

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: eu-central-1

functions:
  app:
    handler: app.handler
    timeout: 60
    description: CORS handler
    events:
      - http:
          path: /proxy
          method: ANY
          cors:
            origins:
              - http://localhost:8081
              - https://studio.kapix.fr
              - https://studio-business.kapix.fr
            allowCredentials: false

package:
  patterns:
    - 'node_modules/**/*'
    - '!node_modules/serverless-offline'
    - '!node_modules/serverless'
    - '!node_modules/.pnpm'
    - '!node_modules/.bin'
    - '!node_modules/.modules.yaml'
    - '!node_modules/typescript'
    - '!README.md'
    - '!pnpm-lock.yaml'
    - '!package-lock.json'
    - '!.vscode'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list