service: cors-proxy

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline #serverless-offline needs to be last in the list


functions:
  corsHello:
    handler: handler.corsHello
    events:
      - http:
          method: get
          path: /
          cors: true
  corsProxy:
    handler: handler.corsProxyGet
    events:
      - http:
          method: get
          path: /proxy
          cors: true